---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: common-proxies
spec:
  selector:
    matchLabels:
      app: common-proxies
  template:
    metadata:
      labels:
        app: common-proxies
    spec:
      containers:
        - name: common-proxies
          image: "{{ .Values.common_proxies.image.repository }}:{{ .Values.common_proxies.image.tag }}"
          imagePullPolicy: {{ .Values.common_proxies.image.pullPolicy }}
          env:
{{ toYaml .Values.common_proxies.environment | indent 12 }}
          ports:
            - name: http
              containerPort: 5000
          readinessProbe:
            httpGet:
              port: http
              path: /health
          livenessProbe:
            httpGet:
              port: http
              path: /health

---
kind: Service
apiVersion: v1
metadata:
  name: common-proxies
spec:
  type: {{ .Values.common_proxies.service.type }}
  ports:
    - port: {{ .Values.common_proxies.service.port }}
      targetPort: http
  selector:
    app: common-proxies

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: common-proxies
{{ if .Values.common_proxies.ingress.annotations }}
  annotations:
{{ toYaml .Values.common_proxies.ingress.annotations | indent 4 }}
{{ end }}
spec:
  {{ if .Values.common_proxies.ingress.className }}
  ingressClassName: {{ .Values.common_proxies.ingress.className }}
  {{ end }}
  rules:
    - host: {{ .Values.common_proxies.ingress.host }}
      http:
        paths:
          - path: {{ .Values.common_proxies.ingress.path }}
            pathType: {{ .Values.common_proxies.ingress.pathType }}
            backend:
              service:
                name: common-proxies
                port:
                  number: {{ .Values.common_proxies.service.port }}
{{ if .Values.common_proxies.ingress.tls }}
  tls:
{{ toYaml .Values.common_proxies.ingress.tls | indent 4 }}
{{ end }}
