name: nextcloud_test
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  crypto: ^3.0.1
  nextcloud:
    path: ../nextcloud
  process_run: ^0.12.3+1

dev_dependencies:
  nit_picking:
    git:
      url: https://github.com/stack11/dart_nit_picking
      ref: f29382f
